name: remote_config_example
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  equatable: ^2.0.5
  firebase_core: ^2.17.0
  firebase_remote_config: ^4.2.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  remote_config_repository:
    path: packages/remote_config_repository

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
