name: remote_config_repository
description: A repository that handles remote config.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  firebase_core: ^2.17.0
  firebase_remote_config: ^4.2.7
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
